import Head from "next/head";
import { useRouter } from "next/router";

import Container from "../../styles/Styled.Container";
import Card from "../../components/Card";

const Question = () => {
  const router = useRouter();
  const { question_id } = router.query;
  return (
    <div>
      <Head>
        <title>Country Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container width='100%' height='100vh'>
        <Card question_id={question_id} />
      </Container>

      <footer></footer>
    </div>
  );
};
export default Question;
