import Head from "next/head";
import Link from "next/link";

import Container from "../styles/Styled.Container";
import { StyledText } from "../components/styled/Text.styled";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Country Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container width='100%' height='100vh'>
        <Link href='questions/1' passHref>
          <StyledText clickable color={({ theme }) => theme.colors.white}>
            Click Here to enter
          </StyledText>
        </Link>
      </Container>

      <footer></footer>
    </div>
  );
};
export default Home;
