import Head from "next/head";

import Container from "../styles/Styled.Container";
import Card from "../components/Card";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Country Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container width='100%' height='100vh'>
        <Card />
      </Container>

      <footer></footer>
    </div>
  );
}
